### PR TITLE
Improvement for templates in `create-aleo-app`

### PR DESCRIPTION
**Pull request by WillXing**
## Motivation

The templates in `create-aleo-app` is great start point for builders.

This PR is to improve the experience and usability by following changes:

- Update program string from concat(+) to string template to improve the readability
- Utilize `localProgramExecution` to use arguments as expected. This can be easier for user to understand the intention and how aleo program executed in app

## Test Plan

Currently no unit test in templates, could be next things to working on. Now test plan is running them locally.

### CODE REVIEW

**Comment by onetrickwolf** [comment]
Thanks for catching these yeah this is much more readable and clearly we meant to do something with those arguments and forgot haha.

Will review these next week need to take some time and update some other areas of the SDK and test.

> Currently no unit test in templates, could be next things to working on. Now test plan is running them locally.

We have some e2e's in the works for this if you have any suggestions or opinions let me know though! I think I want to avoiding including unit tests in the templates themselves just so they can be lighter weight for people trying to start fast. Probably will set it up as some top level folder in `create-aleo-app`

**Comment by WillXing** [comment]
> I think I want to avoiding including unit tests in the templates themselves just so they can be lighter weight for people trying to start fast.

fair point, standalone e2e sounds like a good fit which can test multiple projects regardless the tech stack. 👍

**Comment by WillXing** [comment]
Hi @onetrickwolf , how's things going. Got any time to review/approve this?

**Comment by onetrickwolf** [comment]
Hey @WillXing yeah sorry we've been stress testing the network last two weeks: https://twitter.com/AleoHQ/status/1744816856978915557

Back to normal flow this Monday, hoping to churn through some reviews and general SDK improvements over the next two weeks, sorry for delay appreciate the contribution!

**Review by onetrickwolf — APPROVED** [review]

**Pull request merged**
