### PR TITLE
[Feature] Improve HMR and build performance of aleo.tools

### LINKED ISSUE #617: [Proposal] Improve HMR performance of aleo.tools
## 💥 Proposal

Improve https://aleo.tools compile time and hot module reload time.

Currently takes me over 3 seconds to compile and hot reload the aleo.tools dev environment but we should be able to get that down to ~100ms by doing the following:

- Switching to [Vite](https://vitejs.dev/) 
- Upgrading to React 18
- Integrating [SWC](https://swc.rs/)

### PR DESCRIPTION
**Pull request by onetrickwolf**
## Motivation

Resolves #617 

## Test Plan

Functionality should be identical but compile time and hot reload should be significantly faster (roughly 50x performance in my tests).

### CODE REVIEW

**Comment by onetrickwolf** [comment]
Currently have new build in `website-swc` am keeping old `website` folder separate to easily compare and bench. This branch was also coming off of a branch for #598 will be removing that code before coming out of draft.

**Comment by onetrickwolf** [comment]
Unfortunately, a bug in vite means we still have to use Webpack for production builds, but this PR is still worth merging considering how much it speeds up the dev server spinup and HMR. 

Tracking vite bug here: #628; I will remove the web pack once this bug is resolved.

**Comment by onetrickwolf** [comment]
Some issues with how this deploys to netlify, making a few small changes.

**Review by collinc97 — APPROVED** [review]
LGTM

**Review by iamalwaysuncomfortable — APPROVED** [review]
This looks good, I'd say pending the merge of the new fixes upstream, this looks fine to me.

**Comment by onetrickwolf** [comment]
Okay fixed the vite build.

Had to do a small patch for `wasm-bindgen-rayon` here: https://github.com/GoogleChromeLabs/wasm-bindgen-rayon/compare/main...onetrickwolf:wasm-bindgen-rayon:main

Patch implemented via root (patches do not work in workspaces apparently) `Cargo.toml`: https://github.com/AleoHQ/sdk/pull/618/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R23-R25

I attempted to find a solution that would work for both webpack and vite so I could submit it as a PR to `wasm-bindgen-rayon` but was unable to find a simple one. I may make a PR to them for a feature flag for `non-webpack` bundlers or something though so we can get off this patch eventually or maybe implement the solution in vite.

**Comment by onetrickwolf** [comment]
Okay this should be good to go. Decided to go back to the webpack build for now after some more research I am pretty convinced this is actually best solved with a vite patch rather than patching `wasm-bindgen-rayon`.

Currently deployed to https://staging.aleo.tools/ seems to be fine!

There's a few non-ideal configurations from the hybrid approach but nothing major, still a huge improvement. Hopefully can be cleared up in the near future. In staging will throw that it is missing `index.jsx` due to a difference in how vite and webpack do entry points but will not affect anything.

**Pull request merged**
